# Dockerfile.backend
FROM node:20

WORKDIR /app

COPY apps/meteora-backend/package*.json ./

RUN npm install

COPY apps/meteora-backend/ ./

RUN npx prisma generate

RUN npm run build 

EXPOSE 3000

CMD ["node", "dist/src/main.js"]
