# Dockerfile.frontend
FROM node:20 as build

WORKDIR /app

COPY apps/meteora-frontend/package*.json ./

RUN npm install && npm install -g typescript@latest

COPY apps/meteora-frontend/ ./

COPY tsconfig.json ./tsconfig.json

RUN npm install @types/node --save-dev

COPY apps/libs/graphql-types ./apps/libs/graphql-types

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
